[project]
name = "weather"
version = "0.1.0"
description = "Simple MCP server that provides weather information."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "httpx>=0.28.1",
    "mcp[cli]>=1.19.0",
]
